package fr.delweb.analyzer.Common.utils;

import org.eclipse.jdt.core.dom.IMethodBinding;
import org.eclipse.jdt.core.dom.ITypeBinding;
import fr.delweb.analyzer.Analysis.Models.Graph.MacroGraph.Coupling.PaireClass;
import fr.delweb.analyzer.Analysis.Models.Graph.MicroGraph.CallGraph;

import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public final class IcoUtils {

    public static String createMethodSignature(IMethodBinding binding) {
        if (binding == null) return "unknown.binding";

        StringBuilder signature = new StringBuilder();
        ITypeBinding declaringClass = binding.getDeclaringClass();
        if (declaringClass == null || declaringClass.getQualifiedName().isEmpty()) {
            return "local.class#" + binding.getName();
        }
        signature.append(declaringClass.getErasure().getQualifiedName());
        signature.append("#");
        signature.append(binding.getName());
        signature.append("(");

        ITypeBinding[] parameters = binding.getParameterTypes();
        for (int i = 0; i < parameters.length; i++) {
            signature.append(parameters[i].getErasure().getQualifiedName());
            if (i < parameters.length - 1) {
                signature.append(",");
            }
        }
        signature.append(")");
        return signature.toString();
    }

    public static String simplifySignature(String signature) {
        String[] parts = signature.split("#");
        String classAndPackage = parts[0];
        String methodNameAndParams = parts.length > 1 ? parts[1] : "";

        String className = classAndPackage.substring(classAndPackage.lastIndexOf('.') + 1);

        // On remplace les longs noms de paramètres par "..." pour la clarté
        return className + "#" + methodNameAndParams.replaceAll("\\(.*\\)", "(...)");
    }

    public static String signatureToNameOfClass(String signature) {
        if (signature.isEmpty()){return "";}
        String result = "";
        String afterHash = signature.split("#")[0];
        String[] tabResult = afterHash.split("\\.");
        result = tabResult[tabResult.length-1];
        return result;
    }

    /**
     * Détermine le package de base du projet analysé à partir d'un CallGraph
     * en trouvant le plus long préfixe commun à tous les noms de classes.
     * @param callGraph L'objet contenant le graphe d'appel.
     * @return Le nom du package de base (ex: "com.example.superAppli") ou une chaîne vide.
     */
    public static String determineBasePackage(CallGraph callGraph) {
        // 1. Extraire tous les noms de classes uniques des clés du graphe d'appel.
        //    On utilise un Set pour garantir l'unicité et la performance.
        List<String> classNames = callGraph.getAdjacencyList().keySet().stream()
                .map(signature -> signature.split("#")[0]) // Extrait le nom de la classe de la signature
                .distinct() // Garde uniquement les noms de classes uniques
                .collect(Collectors.toList());

        if (classNames.isEmpty()) {
            return "";
        }

        // 2. L'algorithme du plus long préfixe commun reste identique.
        String longestCommonPrefix = classNames.get(0);
        for (int i = 1; i < classNames.size(); i++) {
            String currentClassName = classNames.get(i);
            while (!currentClassName.startsWith(longestCommonPrefix)) {
                // On retire le dernier segment (après le dernier point)
                int lastDot = longestCommonPrefix.lastIndexOf('.');
                if (lastDot == -1) {
                    return ""; // Pas de préfixe commun
                }
                longestCommonPrefix = longestCommonPrefix.substring(0, lastDot);
            }
        }

        // On a trouvé le préfixe commun le plus long, qui est notre package de base.
        return longestCommonPrefix;
    }

    /**
     * Surcharge de la méthode determineBasePackage.
     * Détermine le package de base du projet à partir d'une collection de PaireClass
     * en trouvant le plus long préfixe commun à tous les noms de classes impliquées.
     *
     * GENERATED BY GEMINI PRO 2.5
     * @param couplingPairs La collection des objets PaireClass résultant de l'analyse de couplage.
     * @return Le nom du package de base (ex: "um.ico.ingenierie") ou une chaîne vide.
     */
    public static String determineBasePackage(Collection<PaireClass> couplingPairs) {
        if (couplingPairs == null || couplingPairs.isEmpty()) {
            return "";
        }

        // 1. Extraire tous les noms de classes uniques des paires.
        // On utilise un Stream pour aplatir les paires et collecter tous les noms.
        // On utilise un Set pour garantir l'unicité automatiquement et efficacement.
        Set<String> classNames = couplingPairs.stream()
                .flatMap(pair -> Stream.of(pair.signClassA, pair.signClassB))
                .filter(Objects::nonNull) // Sécurité pour éviter les NullPointerException
                .collect(Collectors.toSet());

        if (classNames.isEmpty()) {
            return "";
        }

        // Convertir le Set en List pour pouvoir accéder au premier élément.
        List<String> classNamesList = new ArrayList<>(classNames);

        // 2. L'algorithme du plus long préfixe commun reste identique.
        String longestCommonPrefix = classNamesList.get(0);
        // On s'assure de partir d'un nom de package et non d'une classe complète.
        if (longestCommonPrefix.contains(".")) {
            longestCommonPrefix = longestCommonPrefix.substring(0, longestCommonPrefix.lastIndexOf('.'));
        }

        for (String currentClassName : classNamesList) {
            while (!currentClassName.startsWith(longestCommonPrefix)) {
                int lastDot = longestCommonPrefix.lastIndexOf('.');
                if (lastDot == -1) {
                    return ""; // Pas de préfixe commun, on retourne une chaîne vide.
                }
                longestCommonPrefix = longestCommonPrefix.substring(0, lastDot);
            }
        }

        return longestCommonPrefix;
    }



    public static String signatureToQualifiedClassName(String signature) {
        if (signature == null || signature.isEmpty()) {
            return "";
        }
        int hashIndex = signature.indexOf('#');
        if (hashIndex == -1) {
            // Pas de '#', on suppose que c'est déjà un nom de classe ou invalide
            return signature;
        }
        return signature.substring(0, hashIndex);
    }

    public static Set<String> getAllClass_From(List<PaireClass> paireClassList, boolean withBasePackage_NotExternal){
        Set<String> setDeClass = new TreeSet<>();
        String basePackage;

        for (PaireClass paireClass: paireClassList){
            setDeClass.add(paireClass.getSignClassA());
            setDeClass.add(paireClass.getSignClassB());

        }
        if (withBasePackage_NotExternal){
            basePackage = determineBasePackage(paireClassList);
            setDeClass = setDeClass.stream()
                    .filter(str -> str.startsWith(basePackage))
                    .collect(Collectors.toSet());
        } else {
            basePackage = null;
        }


        System.out.println(setDeClass);
        return setDeClass;
    }
}
