/*
 * Generated by Claude Sonnet 4 on Windsurf
 * Supervised by Delhelle Miguel
 * For Java Project Analysis TP1 - TP2 - Restructuration et évolution de logicielle
 *
 * FINAL VERSION integrating D3.js into the user's provided base code.
 */

import cytoscape from 'cytoscape';
import { Chart, registerables } from 'chart.js/auto';
// IMPORT THE D3 RENDERER
import { D3DendrogramRenderer, DendroNode as DendroNodeForRenderer } from './dendogram-d3';

Chart.register(...registerables);

// =================================================================================
// TYPE DEFINITIONS - Updated to include Dendrogram
// =================================================================================

interface MetricsDto {
    [key: string]: number;
}

interface GraphDTO {
    adjacencyList: { [key: string]: Array<{ calleeSignature: string; type: string }> };
}

interface CouplingEdge {
    classA: string;
    classB: string;
    nbrOfLink: number;
    coupling: number;
}

interface TreeCoupling {
    graphCoupling: CouplingEdge[];
}

// Interface for the data from the backend
interface DendroNode {
    leftChild: DendroNode | null;
    rightChild: DendroNode | null;
    hauteurCoupling: number;
    className: string | null;
    classContenu: string[];
    leaf: boolean;
}

// Updated AnalysisResponse to include the dendrogram root
interface AnalysisResponse {
    metricsDto: MetricsDto;
    graphDTO: GraphDTO;
    treeCoupling: TreeCoupling;
    basePackage: string;
    rootDendro: DendroNode; // This field must be in your JSON response
}

// =================================================================================
// MAIN APPLICATION CLASS - Based on your code, with Dendrogram logic added
// =================================================================================

class AnalyzerApp {
    // --- All original properties ---
    private gitUriInput!: HTMLInputElement;
    private analyzeBtn!: HTMLButtonElement;
    private loader!: HTMLElement;
    private errorDiv!: HTMLElement;
    private results!: HTMLElement;
    private metricsCards!: HTMLElement;
    private metricsSummary!: HTMLElement;
    private callGraph!: HTMLElement;
    private couplingGraph!: HTMLElement;
    private callGraphFilterBtn!: HTMLButtonElement;
    private couplingGraphFilterBtn!: HTMLButtonElement;
    private callGraphFullscreenBtn!: HTMLButtonElement;
    private couplingGraphFullscreenBtn!: HTMLButtonElement;
    private fullscreenModal!: HTMLElement;
    private fullscreenGraph!: HTMLElement;
    private fullscreenTitle!: HTMLElement;
    private fullscreenCloseBtn!: HTMLButtonElement;
    private basePackage: string = '';
    private callGraphFilterActive: boolean = false;
    private couplingGraphFilterActive: boolean = false;
    private currentAnalysisData: AnalysisResponse | null = null;
    
    // --- Properties ADDED for Dendrogram ---
    private dendrogramGraph!: HTMLElement;
    private dendrogramFullscreenBtn!: HTMLButtonElement;
    private dendrogramRenderer: D3DendrogramRenderer;
    private currentFullscreenGraph: 'call' | 'coupling' | 'dendrogram' | null = null;

    constructor() {
        // Instantiate the D3 renderer
        this.dendrogramRenderer = new D3DendrogramRenderer();
        this.initializeElements();
        this.bindEvents();
    }

    private initializeElements(): void {
        // --- All original initializations ---
        this.gitUriInput = document.getElementById('gitUri') as HTMLInputElement;
        this.analyzeBtn = document.getElementById('analyzeBtn') as HTMLButtonElement;
        this.loader = document.getElementById('loader') as HTMLElement;
        this.errorDiv = document.getElementById('error') as HTMLElement;
        this.results = document.getElementById('results') as HTMLElement;
        this.metricsCards = document.getElementById('metrics-cards') as HTMLElement;
        this.metricsSummary = document.getElementById('metrics-summary') as HTMLElement;
        this.callGraph = document.getElementById('call-graph') as HTMLElement;
        this.couplingGraph = document.getElementById('coupling-graph') as HTMLElement;
        this.callGraphFilterBtn = document.getElementById('call-graph-filter') as HTMLButtonElement;
        this.couplingGraphFilterBtn = document.getElementById('coupling-graph-filter') as HTMLButtonElement;
        this.callGraphFullscreenBtn = document.getElementById('call-graph-fullscreen') as HTMLButtonElement;
        this.couplingGraphFullscreenBtn = document.getElementById('coupling-graph-fullscreen') as HTMLButtonElement;
        this.fullscreenModal = document.getElementById('fullscreen-modal') as HTMLElement;
        this.fullscreenGraph = document.getElementById('fullscreen-graph') as HTMLElement;
        this.fullscreenTitle = document.getElementById('fullscreen-title') as HTMLElement;
        this.fullscreenCloseBtn = document.getElementById('fullscreen-close') as HTMLButtonElement;
        
        // --- Elements ADDED for Dendrogram ---
        this.dendrogramGraph = document.getElementById('dendrogram-graph') as HTMLElement;
        this.dendrogramFullscreenBtn = document.getElementById('dendrogram-fullscreen') as HTMLButtonElement;
    }

    private bindEvents(): void {
        // --- All original bindings ---
        this.analyzeBtn.addEventListener('click', () => this.analyzeProject());
        this.gitUriInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') this.analyzeProject(); });
        this.callGraphFilterBtn?.addEventListener('click', () => this.toggleCallGraphFilter());
        this.couplingGraphFilterBtn?.addEventListener('click', () => this.toggleCouplingGraphFilter());
        this.callGraphFullscreenBtn?.addEventListener('click', () => this.openFullscreen('call'));
        this.couplingGraphFullscreenBtn?.addEventListener('click', () => this.openFullscreen('coupling'));
        this.fullscreenCloseBtn?.addEventListener('click', () => this.closeFullscreen());
        this.fullscreenModal?.addEventListener('click', (e) => { if (e.target === this.fullscreenModal) this.closeFullscreen(); });
        document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && this.currentFullscreenGraph) this.closeFullscreen(); });

        // --- Binding ADDED for Dendrogram ---
        this.dendrogramFullscreenBtn?.addEventListener('click', () => this.openFullscreen('dendrogram'));
    }

    // --- All original methods are preserved ---
    private showLoader(): void { this.loader.classList.remove('hidden'); this.errorDiv.classList.add('hidden'); this.results.classList.add('hidden'); this.analyzeBtn.disabled = true; }
    private hideLoader(): void { this.loader.classList.add('hidden'); this.analyzeBtn.disabled = false; }
    private showError(message: string): void { this.errorDiv.textContent = message; this.errorDiv.classList.remove('hidden'); }
    private showResults(): void { this.results.classList.remove('hidden'); }
    private formatMetricName(name: string): string { return name.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()); }
    private simplifyClassName(className: string): string { const parts = className.split('.'); return parts[parts.length - 1] || className; }
    private simplifyMethodSignature(signature: string): string { const parts = signature.split('#'); if (parts.length === 2) { const className = parts[0].split('.').pop() || parts[0]; const methodPart = parts[1].split('(')[0]; return `${className}.${methodPart}`; } const lastDot = signature.lastIndexOf('.'); if (lastDot > 0) { return signature.substring(lastDot + 1); } return signature; }
    private shouldIncludeInCallGraph(signature: string): boolean { if (!this.callGraphFilterActive || !this.basePackage) { return true; } return signature.startsWith(this.basePackage); }
    private shouldIncludeInCouplingGraph(className: string): boolean { if (!this.couplingGraphFilterActive || !this.basePackage) { return true; } return className.startsWith(this.basePackage); }
    private closeFullscreen(): void { this.fullscreenModal.classList.add('hidden'); this.currentFullscreenGraph = null; this.fullscreenGraph.innerHTML = ''; }

    private async analyzeProject(): Promise<void> {
        const gitUri = this.gitUriInput.value.trim();
        if (!gitUri) { this.showError('Veuillez saisir une URL Git valide'); return; }
        this.showLoader();
        try {
            const response = await fetch('/api/analyses/git', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ uriGit: gitUri }) });
            if (!response.ok) { throw new Error(`Erreur HTTP: ${response.status}`); }
            const data: AnalysisResponse = await response.json();
            this.currentAnalysisData = data;
            this.basePackage = data.basePackage || '';
            this.displayResults(data);
            this.showResults();
            this.updateFilterButtons();
        } catch (error) { this.showError(`Erreur lors de l'analyse: ${error instanceof Error ? error.message : 'Erreur inconnue'}`); } finally { this.hideLoader(); }
    }

    private displayResults(data: AnalysisResponse): void {
        this.displayMetrics(data.metricsDto);
        this.displayCallGraph(data.graphDTO);
        this.displayCouplingGraph(data.treeCoupling);
        
        // --- CALL TO RENDER DENDROGRAM ADDED ---
        if (data.rootDendro) {
            this.displayDendrogramGraph(data.rootDendro);
        }
    }

    private displayMetrics(metrics: MetricsDto): void {
        this.metricsCards.innerHTML = '';
        Object.entries(metrics).forEach(([key, value]) => {
            const card = document.createElement('div');
            card.className = 'metric-card';
            card.innerHTML = `<h3>${this.formatMetricName(key)}</h3><div class="metric-value">${Number(value).toFixed(2)}</div>`;
            this.metricsCards.appendChild(card);
        });
        const totalMetrics = Object.keys(metrics).length;
        const avgValue = Object.values(metrics).reduce((a, b) => a + b, 0) / totalMetrics;
        this.metricsSummary.innerHTML = `<div class="summary"><p><strong>Résumé:</strong> ${totalMetrics} métriques analysées avec une valeur moyenne de ${avgValue.toFixed(2)}</p></div>`;
    }

    // --- NEW METHOD to handle Dendrogram display ---
    private displayDendrogramGraph(rootNode: DendroNode): void {
        if (this.dendrogramGraph) {
            this.dendrogramRenderer.render(rootNode as DendroNodeForRenderer, this.dendrogramGraph);
        }
    }
    
    // --- (Methods below are from your original file, unchanged) ---

    private displayCallGraph(graphData: GraphDTO): void {
        this.callGraph.innerHTML = '';
        const elements = this.convertAdjacencyListToCytoscape(graphData.adjacencyList);
        cytoscape({ container: this.callGraph, elements, style: [ { selector: 'node', style: { 'background-color': '#3498db', 'label': 'data(label)', 'text-valign': 'center', 'text-halign': 'center', 'color': '#2c3e50', 'font-size': '14px', 'font-weight': 'bold', 'text-outline-width': 2, 'text-outline-color': '#fff', 'text-outline-opacity': 0.8, 'width': '80px', 'height': '80px', 'border-width': 2, 'border-color': '#2980b9', 'text-wrap': 'wrap', 'text-max-width': '70px' } }, { selector: 'edge', style: { 'width': 2, 'line-color': '#95a5a6', 'target-arrow-color': '#95a5a6', 'target-arrow-shape': 'triangle', 'curve-style': 'bezier' } } ], layout: { name: 'cose', animate: true, animationDuration: 1000, nodeRepulsion: 10000, nodeOverlap: 20, idealEdgeLength: 120, edgeElasticity: 200, nestingFactor: 5, gravity: 80, numIter: 1000, initialTemp: 200, coolingFactor: 0.95, minTemp: 1.0 } });
    }

    private displayCouplingGraph(couplingData: TreeCoupling): void {
        this.couplingGraph.innerHTML = '';
        const elements = this.convertCouplingToCytoscape(couplingData.graphCoupling);
        cytoscape({ container: this.couplingGraph, elements: elements, style: [ { selector: 'node', style: { 'background-color': (ele: any) => { const coupling = ele.data('coupling') || 0; const intensity = Math.min(coupling, 1); return `rgb(${Math.round(52 + (231 - 52) * intensity)}, ${Math.round(152 + (76 - 152) * intensity)}, ${Math.round(219 + (60 - 219) * intensity)})`; }, 'label': 'data(label)', 'text-valign': 'center', 'text-halign': 'center', 'color': '#2c3e50', 'font-size': '12px', 'font-weight': 'bold', 'text-outline-width': 2, 'text-outline-color': '#fff', 'text-outline-opacity': 0.9, 'width': '80px', 'height': '80px', 'border-width': 3, 'border-color': '#c0392b', 'text-wrap': 'wrap', 'text-max-width': '70px' } }, { selector: 'edge', style: { 'width': (ele: any) => Math.max(3, Math.min(15, (ele.data('coupling') || 0) * 50)), 'label': 'data(label)', 'font-size': '10px', 'color': '#2c3e50', 'text-background-color': '#fff', 'text-background-opacity': 0.8, 'text-background-padding': '2px', 'text-border-width': 1, 'text-border-color': '#ccc', 'text-border-opacity': 0.8, 'line-color': (ele: any) => { const coupling = ele.data('coupling') || 0; const intensity = Math.min(coupling / 10, 1); return `rgb(${Math.round(149 + (231 - 149) * intensity)}, ${Math.round(165 + (76 - 165) * intensity)}, ${Math.round(166 + (60 - 166) * intensity)})`; }, 'curve-style': 'bezier', 'opacity': (ele: any) => Math.max(0.5, Math.min(1, 0.5 + (ele.data('coupling') || 0) / 20)) } } ], layout: { name: 'cose', animate: true, animationDuration: 1000, nodeRepulsion: 8000, nodeOverlap: 20, idealEdgeLength: 100, edgeElasticity: 200, nestingFactor: 5, gravity: 80, numIter: 1000, initialTemp: 200, coolingFactor: 0.95, minTemp: 1.0 } });
    }

    private convertAdjacencyListToCytoscape(adjacencyList: { [key: string]: any[] }): any[] {
        const elements: any[] = [];
        const nodes = new Set<string>();
        Object.keys(adjacencyList).forEach(source => { if (this.shouldIncludeInCallGraph(source)) { nodes.add(source); } adjacencyList[source].forEach(edge => { if (edge.calleeSignature && this.shouldIncludeInCallGraph(edge.calleeSignature)) { if (this.shouldIncludeInCallGraph(source)) { nodes.add(edge.calleeSignature); } } }); });
        nodes.forEach(node => { const simplifiedLabel = this.simplifyMethodSignature(node); elements.push({ data: { id: node, label: simplifiedLabel, fullSignature: node } }); });
        Object.entries(adjacencyList).forEach(([source, edges]) => { if (this.shouldIncludeInCallGraph(source)) { edges.forEach(edge => { if (edge.calleeSignature && this.shouldIncludeInCallGraph(edge.calleeSignature)) { elements.push({ data: { id: `${source}-${edge.calleeSignature}`, source: source, target: edge.calleeSignature, type: edge.type } }); } }); } });
        return elements;
    }

    private convertCouplingToCytoscape(couplingEdges: CouplingEdge[]): any[] {
        const elements: any[] = [];
        const nodes = new Set<string>();
        const processedPairs = new Set<string>();
        couplingEdges.forEach(edge => { if (this.shouldIncludeInCouplingGraph(edge.classA)) { nodes.add(edge.classA); } if (this.shouldIncludeInCouplingGraph(edge.classB)) { nodes.add(edge.classB); } });
        nodes.forEach(node => { const nodeCoupling = couplingEdges.filter(e => e.classA === node || e.classB === node).reduce((sum, e) => sum + e.coupling, 0); const simplifiedLabel = this.simplifyClassName(node); elements.push({ data: { id: node, label: simplifiedLabel, fullName: node, coupling: nodeCoupling } }); });
        couplingEdges.forEach(edge => { if (this.shouldIncludeInCouplingGraph(edge.classA) && this.shouldIncludeInCouplingGraph(edge.classB)) { const pairKey = [edge.classA, edge.classB].sort().join('-'); if (!processedPairs.has(pairKey)) { processedPairs.add(pairKey); const couplingPercentage = Math.round(edge.coupling * 100); elements.push({ data: { id: `${edge.classA}-${edge.classB}`, source: edge.classA, target: edge.classB, coupling: edge.coupling, nbrOfLink: edge.nbrOfLink, label: `${couplingPercentage}%` } }); } } });
        return elements;
    }

    private toggleCallGraphFilter(): void { this.callGraphFilterActive = !this.callGraphFilterActive; this.updateFilterButtons(); if (this.currentAnalysisData) { this.displayCallGraph(this.currentAnalysisData.graphDTO); } }
    private toggleCouplingGraphFilter(): void { this.couplingGraphFilterActive = !this.couplingGraphFilterActive; this.updateFilterButtons(); if (this.currentAnalysisData) { this.displayCouplingGraph(this.currentAnalysisData.treeCoupling); } }
    
    private updateFilterButtons(): void {
        if (this.callGraphFilterBtn) { this.callGraphFilterBtn.classList.toggle('active', this.callGraphFilterActive); this.callGraphFilterBtn.textContent = this.callGraphFilterActive ? `Afficher tout (actuellement: ${this.basePackage}*)` : 'Filtrer par package de base'; }
        if (this.couplingGraphFilterBtn) { this.couplingGraphFilterBtn.classList.toggle('active', this.couplingGraphFilterActive); this.couplingGraphFilterBtn.textContent = this.couplingGraphFilterActive ? `Afficher tout (actuellement: ${this.basePackage}*)` : 'Filtrer par package de base'; }
    }

    private openFullscreen(graphType: 'call' | 'coupling' | 'dendrogram'): void {
        this.currentFullscreenGraph = graphType;
        this.fullscreenModal.classList.remove('hidden');
        
        const data = this.currentAnalysisData;
        if (!data) return;

        switch (graphType) {
            case 'call':
                this.fullscreenTitle.textContent = 'Graphe d\'Appels - Plein Écran';
                this.displayCallGraphInContainer(data.graphDTO, this.fullscreenGraph);
                break;
            case 'coupling':
                this.fullscreenTitle.textContent = 'Graphe de Couplage - Plein Écran';
                this.displayCouplingGraphInContainer(data.treeCoupling, this.fullscreenGraph);
                break;
            case 'dendrogram':
                this.fullscreenTitle.textContent = 'Dendrogramme - Plein Écran';
                if (data.rootDendro) {
                    this.dendrogramRenderer.render(data.rootDendro as DendroNodeForRenderer, this.fullscreenGraph);
                }
                break;
        }
    }
    
    private displayCallGraphInContainer(graphData: GraphDTO, container: HTMLElement): void {
        container.innerHTML = '';
        const elements = this.convertAdjacencyListToCytoscape(graphData.adjacencyList);
        cytoscape({ container: container, elements: elements, style: [ { selector: 'node', style: { 'background-color': '#3498db', 'label': 'data(label)', 'text-valign': 'center', 'text-halign': 'center', 'color': '#2c3e50', 'font-size': '14px', 'font-weight': 'bold', 'text-outline-width': 2, 'text-outline-color': '#fff', 'text-outline-opacity': 0.8, 'width': '80px', 'height': '80px', 'border-width': 2, 'border-color': '#2980b9', 'text-wrap': 'wrap', 'text-max-width': '70px' } }, { selector: 'edge', style: { 'width': 2, 'line-color': '#95a5a6', 'target-arrow-color': '#95a5a6', 'target-arrow-shape': 'triangle', 'curve-style': 'bezier' } } ], layout: { name: 'cose', animate: true, animationDuration: 1500, nodeRepulsion: 12000, nodeOverlap: 30, idealEdgeLength: 150, edgeElasticity: 200, nestingFactor: 5, gravity: 60, numIter: 1200, initialTemp: 300, coolingFactor: 0.95, minTemp: 1.0 } });
    }
    
    private displayCouplingGraphInContainer(couplingData: TreeCoupling, container: HTMLElement): void {
        container.innerHTML = '';
        const elements = this.convertCouplingToCytoscape(couplingData.graphCoupling);
        cytoscape({ container: container, elements: elements, style: [ { selector: 'node', style: { 'background-color': (ele: any) => { const coupling = ele.data('coupling') || 0; const intensity = Math.min(coupling, 1); return `rgb(${Math.round(52 + (231 - 52) * intensity)}, ${Math.round(152 + (76 - 152) * intensity)}, ${Math.round(219 + (60 - 219) * intensity)})`; }, 'label': 'data(label)', 'text-valign': 'center', 'text-halign': 'center', 'color': '#2c3e50', 'font-size': '12px', 'font-weight': 'bold', 'text-outline-width': 2, 'text-outline-color': '#fff', 'text-outline-opacity': 0.9, 'width': '80px', 'height': '80px', 'border-width': 3, 'border-color': '#c0392b', 'text-wrap': 'wrap', 'text-max-width': '70px' } }, { selector: 'edge', style: { 'width': (ele: any) => Math.max(3, Math.min(15, (ele.data('coupling') || 0) * 50)), 'label': 'data(label)', 'font-size': '10px', 'color': '#2c3e50', 'text-background-color': '#fff', 'text-background-opacity': 0.8, 'text-background-padding': '2px', 'text-border-width': 1, 'text-border-color': '#ccc', 'text-border-opacity': 0.8, 'line-color': (ele: any) => { const coupling = ele.data('coupling') || 0; const intensity = Math.min(coupling / 10, 1); return `rgb(${Math.round(149 + (231 - 149) * intensity)}, ${Math.round(165 + (76 - 165) * intensity)}, ${Math.round(166 + (60 - 166) * intensity)})`; }, 'curve-style': 'bezier', 'opacity': (ele: any) => Math.max(0.5, Math.min(1, 0.5 + (ele.data('coupling') || 0) / 20)) } } ], layout: { name: 'cose', animate: true, animationDuration: 1500, nodeRepulsion: 15000, nodeOverlap: 30, idealEdgeLength: 180, edgeElasticity: 200, nestingFactor: 5, gravity: 60, numIter: 1200, initialTemp: 300, coolingFactor: 0.95, minTemp: 1.0 } });
    }
}

// Initialisation de l'application
document.addEventListener('DOMContentLoaded', () => {
    new AnalyzerApp();
});