package um.ico.ingenierie.Analysis.Models.Graph.MacroGraph.Dendro;

import um.ico.ingenierie.Analysis.Models.Graph.MacroGraph.Coupling.PaireClass;
import um.ico.ingenierie.Common.utils.IcoUtils;
import um.ico.ingenierie.Common.utils.PairNormalisation;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;

public class DendroNode{

    private DendroNode leftChild;
    private DendroNode rightChild;
    //private DendroNode parent = null;

    private double hauteurCoupling;

    private String className;

    //Conteneur final
    // On utilise Set pour avoir des éléments unique et non ordonnées
    //private Set<String> classContenu;

    // Constructeur vide protégé pour peut être des itérations plus tard avec des librarie comme JPA Hibernate
    // Qui en nécessite par défaut
    protected DendroNode(){};

    // Constructeur pour les Noeuds feuille
    public DendroNode(String className){
        this.leftChild = null;
        this.rightChild = null;
        this.hauteurCoupling = 1.0;
        this.className = className;
    }

    //Root DendroNode

    //Constructeur pour les noeuds représentant les fusions entre deux noeuds

    public DendroNode(DendroNode child1, DendroNode child2, double couplingValue) {
        this.leftChild = child1;
        this.rightChild = child2;
        this.hauteurCoupling = couplingValue;

        //Identique à PairClass, essentiel au bon fonctionnement
        String[] ordered = PairNormalisation.normalizePair(child1.className, child2.className);
        this.className = ""+ordered[0] + "#" + ordered[1];
    }

    public boolean isLeaf() {
        return leftChild == null && rightChild == null;
    }


    public DendroNode getLeftChild() {
        return leftChild;
    }

    public DendroNode getRightChild() {
        return rightChild;
    }

    public double getHauteurCoupling() {
        return hauteurCoupling;
    }

    public String getClassName() {
        return className;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DendroNode)) return false;
        DendroNode that = (DendroNode) o;

        if (isLeaf() && that.isLeaf()) {
            return Objects.equals(className, that.className);
        }

        if (!isLeaf() && !that.isLeaf()) {
            // ordre indépendant
            return (Objects.equals(leftChild, that.leftChild) && Objects.equals(rightChild, that.rightChild)) ||
                    (Objects.equals(leftChild, that.rightChild) && Objects.equals(rightChild, that.leftChild));
        }

        return false;
    }

    @Override
    public int hashCode() {
        if (isLeaf()) {
            return Objects.hash(className);
        }

        // ordre indépendant et plus robuste que +
        int h1 = leftChild.hashCode();
        int h2 = rightChild.hashCode();
        return h1 ^ h2; // XOR = commutatif
    }

    public int couplingInProportion(){
        double tmp = this.hauteurCoupling*100.0;
        return (int) tmp;
    }

    @Override
    public String toString() {
        return "DendroNode{" +
                "leftChild=" + leftChild +
                ", rightChild=" + rightChild +
                ", hauteurCoupling=" + hauteurCoupling +
                ", className='" + className + '\'' +
                ", isLeaf=" + isLeaf() +
                '}';
    }

    //Generated by ChatGpt 4.5 (OpenAI)
    public boolean containsClass(String name) {
        // 1) Si c'est une feuille → on compare directement son nom
        if (this.isLeaf()) {
            return this.className.equals(name);
        }
        boolean leftContains = false;
        boolean rightContains = false;

        if (leftChild != null) {
            leftContains = leftChild.containsClass(name);
        }
        if (rightChild != null) {
            rightContains = rightChild.containsClass(name);
        }

        return leftContains || rightContains;
    }
    //Generated by ChatGpt 4.5 (OpenAI)
    /**
     * Retourne la concaténation de tous les className des feuilles du sous-arbre.
     */
    public List<String> getAllClassNames() {
        List<String> sb = new ArrayList<>();
        collectClassNames(sb);
        return sb;
    }

    //Generated by ChatGpt 4.5 (OpenAI)
    /**
     * Méthode récursive privée qui remplit le StringBuilder avec les className.
     */
    private void collectClassNames(List<String> sb) {
        if (this.isLeaf()) {
            sb.add(this.className);
            return;
        }

        if (leftChild != null) {
            leftChild.collectClassNames(sb);
        }
        if (rightChild != null) {
            rightChild.collectClassNames(sb);
        }
    }
}
